language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y fftw3 libnetcdf-dev cmake

before_script:
  - mkdir build
  - cd build
  - cmake -DSYST=ubuntu ..

script: make -j 4
