language: cpp

compiler:
  - gcc
  - gfortran

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y fftw3 libfftw3-dev libnetcdf-dev libnetcdf-c++4 libnetcdf-c++4-dev cmake libopenmpi-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DSYST=ubuntu ..

script: make -j 4
